// packages/components/Playground/output/react/src/components/Button/button.tsx
"use client";
import * as React from "react";
import SubButton from "@components/SubButton/sub-button";

function Button(props: any) {
  return (
    <>
      <div>
        <button />

        <button className="active" />

        <SubButton />
      </div>
      <style jsx>{`
        button {
          color: aqua;
        }
        button.active {
          background-color: #000;
          color: #fff;
        }
      `}</style>
    </>
  );
}

export default Button;

// packages/components/Playground/output/vue/vue3/src/components/Button/button.vue
<template>
  <div>
    <button></button>
    <button class="active"></button>
    <sub-button></sub-button>
  </div>
</template>

<script lang="ts">
import SubButton from "@components/SubButton/sub-button.vue";

export default {
  name: "button",
  components: { SubButton: SubButton },
};
</script>

<style scoped>
button {
  color: aqua;
}
button.active {
  background-color: #000;
  color: #fff;
}
</style>
