// packages/components/Playground/output/vue/vue3/src/components/SuperInput/super-input.vue
<template>
  <div class="my-super-duper-input-field">
    <label :for="name">{{ label }}</label>
    <input
      :id="name"
      :name="name"
      :value="value"
      @input="$emit('update:modelValue', $event.target.value)"
    />

    <template v-if="errorMessage">
      <p class="form-message danger">{{ errorMessage }}</p>
    </template>
  </div>
</template>

<script lang="ts">
interface Props {
  name: string;
  label: string;
  value: string;
  errorMessage?: string;
}

const props = defineProps<Props>();
export default {
  name: "super-input-field",
};
</script>

// packages/components/Playground/output/react/src/components/SuperInput/super-input.tsx
"use client";
import * as React from "react";

interface Props {
  name: string;
  label: string;
  value: string;
  onUpdateValue: (val: string) => void;
  errorMessage?: string;
}

function SuperInputField(props: Props) {
  return (
    <>
      <div className="my-super-duper-input-field">
        <label htmlFor={props.name}>{props.label}</label>

        <input
          id={props.name}
          name={props.name}
          value={props.value}
          onChange={(event) => props.onUpdateValue(event.target.value)}
        />

        {props.errorMessage ? (
          <>
            <p className="form-message danger">{props.errorMessage}</p>
          </>
        ) : null}
      </div>
      <style jsx>{``}</style>
    </>
  );
}

export default SuperInputField;
